[alembic]
script_location = alembic

[loggers]
keys = root

[handlers]
keys = konsole

[formatters]
keys = einfach

[logger_root]
level = WARNING
handlers = konsole

[handler_konsole]
class = StreamHandler
args = (sys.stderr,)
formatter = einfach

[formatter_einfach]
format = %(levelname)s %(message)s
